export const USERALREADEXIST = "USERALREADEXIST"
export const USERNOTFOUND = "USERNOTFOUND"

export const INVALIDPASSWORD = "INVALIDPASSWORD"
export const INVALIDEMAIL = "INVALIDEMAIL"
export const INVALIDUSERID = "INVALIDUSERID"
export const INVALIDINPUT = "INVALIDINPUT"
export const INVALIDIMAGE = "INVALIDIMAGE"
export const INVALIDCOMFIRMPASSWORD = "INVALIDCOMFIRMPASSWORD"

export const USERNOTGLOGEDIN = "USERNOTGLOGEDIN"
export const USERALREADYGLOGEDIN = "USERALREADYGLOGEDIN"
export const REFRESHTOKENEXPIRED = "REFRESHTOKENEXPIRED"
export const AUTHTOKENEXPIRED = "AUTHTOKENEXPIRED"
export const TOKENNOTFOUND = "TOKENNOTFOUND"

export const SERVERERROR = "SERVERERROR"

export const JWTERROR = "JWTERROR"

export const OTPRECORDNOTFOUND = "OTPRECORDNOTFOUND"
export const INVALIDOTP = "INVALIDOTP"
