// sign up error 
export type USERALREADEXIST = "USERALREADEXIST"
export type USERNOTFOUND = "USERNOTFOUND"

export type INVALIDPASSWORD = "INVALIDPASSWORD"
export type INVALIDINPUT = "INVALIDINPUT"
export type INVALIDIMAGE = "INVALIDIMAGE"
export type INVALIDCOMFIRMPASSWORD = "INVALIDCOMFIRMPASSWORD"
export type EMAILALAREADTAKEN = "EMAILALAREADTAKEN"
export type USERIDALREADTAKEN = "USERIDALREADTAKEN"

export type USERNOTGLOGEDIN = "USERNOTGLOGEDIN"
export type USERALREADYGLOGEDIN = "USERALREADYGLOGEDIN"
export type REFRESHTOKENEXPIRED = "REFRESHTOKENEXPIRED"
export type AUTHTOKENEXPIRED = "AUTHTOKENEXPIRED"
export type TOKENNOTFOUND = "TOKENNOTFOUND"

export type SERVERERROR = "SERVERERROR"

export type JWTERROR = "JWTERROR"

export type OTPRECORDNOTFOUND = "OTPRECORDNOTFOUND"
export type INVALIDOTP = "INVALIDOTP"